from __future__ import annotations

import json
from pathlib import Path

from .models import Location, ScanResult


def render_report(result: ScanResult, output_format: str = "text") -> str:
    if output_format == "json":
        return json.dumps(result.to_dict(), indent=2, sort_keys=True)
    if output_format == "markdown":
        return render_markdown(result)
    return render_text(result)


def render_text(result: ScanResult) -> str:
    lines = [
        f"envradar scanned {result.scanned_files} files.",
        f"Required runtime vars: {len(result.required_runtime)}",
        f"Documented vars: {len(result.keys_for('documented'))}",
        "",
    ]
    lines.extend(render_text_section(result, "Missing from .env.example", result.missing_from_examples))
    lines.append("")
    lines.extend(render_text_section(result, "Documented but not used", result.unused_in_examples))
    lines.append("")
    lines.extend(render_text_section(result, "Present locally but not documented", result.local_only))
    lines.append("")
    lines.extend(render_text_section(result, "Workflow-only secrets or vars", result.workflow_only))
    return "\n".join(lines).rstrip() + "\n"


def render_text_section(result: ScanResult, title: str, names: list[str]) -> list[str]:
    lines = [f"{title} ({len(names)})"]
    if not names:
        lines.append("  - none")
        return lines
    for name in names:
        lines.append(f"  - {name} -- {compact_locations(result.all_locations_for(name))}")
    return lines


def render_markdown(result: ScanResult) -> str:
    sections = [
        f"# envradar report\n\nScanned **{result.scanned_files}** files.",
        markdown_section(result, "Missing from .env.example", result.missing_from_examples),
        markdown_section(result, "Documented but not used", result.unused_in_examples),
        markdown_section(result, "Present locally but not documented", result.local_only),
        markdown_section(result, "Workflow-only secrets or vars", result.workflow_only),
    ]
    return "\n\n".join(sections).rstrip() + "\n"


def markdown_section(result: ScanResult, title: str, names: list[str]) -> str:
    if not names:
        return f"## {title}\n\n_None._"
    rows = [(name, compact_locations(result.all_locations_for(name))) for name in names]
    return f"## {title}\n\n" + markdown_table(("Variable", "Locations"), rows)


def markdown_table(headers: tuple[str, ...], rows: list[tuple[str, ...]]) -> str:
    header_line = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join("---" for _ in headers) + " |"
    body = ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join([header_line, separator, *body])


def compact_locations(locations: list[Location], limit: int = 3) -> str:
    rendered = [location.display() for location in locations]
    head = ", ".join(rendered[:limit])
    if len(rendered) <= limit:
        return head
    return f"{head} (+{len(rendered) - limit} more)"


def write_env_example(result: ScanResult, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tracked = sorted(result.required_runtime | result.keys_for("documented"))
    lines = [
        "# Generated by envradar.",
        "# Fill in real values locally. Do not commit secrets.",
        "",
    ]
    for name in tracked:
        value = result.example_values.get(name, result.config.placeholders.get(name, ""))
        lines.append(f"{name}={value}")
    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_docs_markdown(result: ScanResult, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, ...]] = []
    for name in result.all_variables:
        rows.append(
            (
                name,
                yesno(name in result.keys_for("code")),
                yesno(name in result.keys_for("documented")),
                yesno(name in result.keys_for("local")),
                yesno(name in result.keys_for("compose")),
                yesno(name in result.keys_for("workflow_secrets") or name in result.keys_for("workflow_vars")),
                compact_locations(result.all_locations_for(name), limit=2),
            )
        )
    content = [
        "# Environment variables",
        "",
        "Generated by envradar. This file intentionally does **not** include local secret values.",
        "",
        markdown_table(
            ("Variable", "Code", "Example", "Local", "Compose", "Workflow", "Locations"),
            rows,
        ) if rows else "_No variables detected._",
        "",
    ]
    output_path.write_text("\n".join(content), encoding="utf-8")


def yesno(value: bool) -> str:
    return "yes" if value else "no"
